#!/usr/bin/env python

import rospy
import sys, select, tty, termios
from std_msgs.msg import String
from geometry_msgs.msg import Twist



print(
"""
-------------------------------------------------------

			   ^

	spin L: Q	   w	        spin R: E
			forward


       < Left a 			Right d >

			 back
			  s
		  
		
	Raise : Z	  		Lower : X 


	Hover : F			Quit : CTRL+C

--------------------------------------------------------
		     NIYAS SALIM
--------------------------------------------------------
"""
)
if __name__ == '__main__':
	rospy.init_node("keyboard_driver")
	key_pub = rospy.Publisher('/turtle1/cmd_vel', Twist, queue_size=1)
	
	rate = rospy.Rate(1)
	msg = Twist()

	#msg.linear.x = -0.8	#Linear speed (+ forward , - Reverse)	meter/second
	#msg.angular.z =0	#radian/second

	old_attr = termios.tcgetattr(sys.stdin)
	tty.setcbreak(sys.stdin.fileno())
	

while not rospy.is_shutdown():
	if select.select([sys.stdin], [], [], 0)[0] == [sys.stdin]:	
		if (sys.stdin.read(1)) == 'w':	
			msg.linear.x = 0.8	#Linear speed (+ forward , - Reverse)	meter/second
		if (sys.stdin.read(1)) == 's':	
			msg.linear.x = -0.8	
		if (sys.stdin.read(1)) == 'a':	
			msg.angular.z = 0.5	#angular speed ( left , right)	meter/second
		if (sys.stdin.read(1)) == 'd':	
			msg.angular.z = -0.5
#		key_pub.publish(sys.stdin.read(1))
		key_pub.publish(msg)
termios.tcsetattr(sys.stdin, termios.TCSADRAIN, old_attr) 
rate.sleep()


#publishing data is in sys.stdin. eg:(sys.stdin.read(1))
